language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
before_install:
  chmod +x gradlew # gradlew 실행 권한 부여 - git push 전에 update를 사용해서 권한을 부여하는 방법이 있으니 찾아볼 것

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - gudah13@naver.com