language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
before_install:
  chmod +x gradlew # gradlew 실행 권한 부여 - git push 전에 update를 사용해서 권한을 부여하는 방법이 있으니 찾아볼 것

before_deploy:
  - zip -r freelec-springboot2-webservice * # 현재 위치 모든 파일을 이 이름으로 zip 압축
  - mkdir -p deploy # 디렉토리 생성
  - mv freelec-springboot2-webservice.zip deploy/freelect-springboot2-webservice.zip # file 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot2-s3-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy # deploy전에 생성한 디렉토리 지정
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: freelec-springboot2-s3-build # S3 버킷
    key: freelec-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: freelec-springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: freelec-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - gudah13@naver.com