version: 0.0 #CodeDeploy 버전. 프로젝트 버전이 아니면 0.0 외의 버전을 사용시 에러가 발생.
os: linux
files:
  - source:  / #CodeDeploy에서 전달해 준 파일중 destination으로 이동시킬 대상 지정.
    destination: /home/ec2-user/app/step3/zip/ #source에서 지정된 파일을 받을 위치. Jar를 실행하는 대상위치가 됨.
    overwrite: yes #기존 파일에 대한 덮어쓰기 설정.
# CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 가지도록 설정.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# CodeDeploy 배포 단계에서 실행할 명렁어들을 지정.
hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ec2-user